### ISSUE TITLE
Add leantrx into your custom firmware

### ISSUE THREAD

**Issue by rkiendl** [unixpunk/PlutoWeb#24]
the Features of leantrx would be a great Addition to your custom build. would be great if You can allign with the author and add this to your cool Software. More Info could be found here and thanks for considering  http://www.pabr.org/radio/leantrx/leantrx.en.html

**Comment by unixpunk** [comment]
Should be doable and fairly easy it looks like.  Never heard of this before, I agree it would make a nice addition!  Thanks!

**Comment by unixpunk** [comment]
Thinking I can have this in an image this week, though @ImDroided would need to add the options to the webUI for easy usage, otherwise you'll have to use config.txt to change the running program.  More to come.

**Comment by unixpunk** [comment]
https://github.com/unixpunk/PlutoWeb/commit/110696138eee10f332770df0f64215f6a7a6efa7  Latest image has leansdr binaries and leantrx at http://.../leantrx.  You'll need to use plutoweb to select SoapyRemote as the running program because it doesn't lock the device until it has a request.

Problem is I can't get leantrx to work at all.  I had to compile the leaniio* tools without lzma since that's not available on the pluto, at least not that I can find in buildroot.  Not sure if that's the reason for the issue or not though, not familiar with these tools at all.

@rkiendl Please test and let me know your thoughts on possible fixes.

**Comment by LamaBleu** [comment]
Hi unixpunk and @ImDroided , first thanks for the nice work on ADALM-PLUTO
Just upgraded to 2.7 !
DVB is working out of stock. It's now OK for me on FM after removing --pump parameter (twice) in mlmrx.cgi
May someone try, to confirm please?
Btw your github size is growing to 1GB, downloading images folder from github is enough for basic users. Cheers.

**Comment by unixpunk** [comment]
Thanks @LamaBleu, I followed your notes here rather than take the files from the update.zip.  They're included in the latest update.zip on here as well if you have it on your network and updates enabled: https://github.com/unixpunk/PlutoWeb/commit/e573c3625223bc109594b3b2d2b4401e7c6d1137

ImDroided working on some other stuff as well so will have a new image later this week.  If you don't want to SSH, you can just use the plutoweb ui and click soapyremote to release the radio.

**Comment by rkiendl** [comment]
i can confirm that the +x for the cgi files is a fix. some for removing the --pmp Parameter. 
maybe the author of leantrx has an idea why and the purpose of the parameter

**Comment by LamaBleu** [comment]
Hi @unixpunk sorry to disturb, had again a permissions issues updating through update.zip . 
Not a big deal for me , but might interest others in trouble, hope this can help.

Have to say my firmware is still 2.7, and I'm usually perfoming updates by copying the zip/md5sum files to the PLUTO usb drive.
I found yesterday an error during the unzip sequence, files are not copied to / and update fails.
However /etc/motd is reporting a successful update.
We can see this looking on permissions for /leantrx/cgi-bin files, old issue...
I reproduced my issue directly on the pluto, please have a look below. This is linked to some unzip function  not implemented on the pluto side.
To be sure, I made a buildtgz.sh , modified  updatewatch.sh to use tar.gz format instead, and it works better.
Thanks again for all :)

Here is the error, from the pluto :
```
# cp /tmp/update.zip /root
# ls
plutoweb.conf      update.zip
# md5sum update.zip > update.zip.md5sum
# cat update.zip.md5sum 
2d7dc99ccf354ca53fb5894f19abc2ac  update.zip
# ls
plutoweb.conf      update.zip         update.zip.md5sum
# updatewatch.sh 
Found /root/update.zip.md5sum, checking for /root/update.zip
Found /root/update.zip
Archive:  /root/update.zip
    linking: lib/libSoapySDR.so      -> libSoapySDR.so.0.7 
    linking: lib/libSoapySDR.so.0.7  -> libSoapySDR.so.0.7.0 
    linking: www/index.html          -> index.htm 
    linking: www/cgi-bin/leantrx     -> ../../leantrx/cgi-bin/ 
    linking: www/leantrx             -> ../leantrx/html/ 
finishing deferred symbolic links:
  lib/libSoapySDR.so     -> libSoapySDR.so.0.7
lchmod (file attributes) error: Function not implemented
  lib/libSoapySDR.so.0.7 -> libSoapySDR.so.0.7.0
lchmod (file attributes) error: Function not implemented
  www/index.html         -> index.htm
lchmod (file attributes) error: Function not implemented
  www/cgi-bin/leantrx    -> ../../leantrx/cgi-bin/
lchmod (file attributes) error: Function not implemented
  www/leantrx            -> ../leantrx/html/
lchmod (file attributes) error: Function not implemented
/root/update.zip update complete!
^C
# ls -l /leantrx/cgi-bin/
total 28
-rw-r--r--    1 root     root           775 Aug  1  2018 cgiutils.sh
-rwxr-xr-x    1 root     root          1358 Aug  1  2018 dvbrx.cgi
-rwxr-xr-x    1 root     root           770 Aug 15  2018 dvbtx.cgi
-rw-r--r--    1 root     root          1526 Aug  1  2018 getstream.cgi
-rwxr-xr-x    1 root     root          1033 Aug  2  2018 mlmrx.cgi
-rw-r--r--    1 root     root           395 Aug  1  2018 recordings.cgi
-rwxr-xr-x    1 root     root           364 Aug  1  2018 sysinfo.cgi
# 

```

**Comment by unixpunk** [comment]
This is a known issue with zip on the pluto, it won't update permissions, BUT it will lay those files down again if they don't exist or if a flag is changed on the unzip command.  I think if you check in that script that I use the 'only new files' option on unzip, removing this flag should cause all files to be overwritten with the correct perms.  That's likely the easiest fix.

Side note, you don't need the md5sum for the update, the script looks for the md5sum first, if it sees it, it then looks for the update.zip and compares the hash.  If it finds the update.zip and NO md5sum, it will install it without a second look.  :)

It also supports dropping that update.zip into the USB mass-storage on the pluto and ejecting for updates.  

In RE to updates, I will be changing the script so that you don't need to manually run it.  Auto-updates will mean "auto-download from web" but I'll have it still process any update zips it finds there, unlike today if updates are disabled.  I'll create a new issue for that.
