### ISSUE TITLE
Error 22 on LeanTRX

### ISSUE THREAD

**Issue by KR0SIV** [unixpunk/PlutoWeb#52]
When I attempt to use the leantrx beacon I get the following error.

leantsgen | leandvbtx --cr 7/8 --const QPSK -f 2 --s16 --power 0 --rrc-rej 10 -v | leaniiotx --bufsize 65536 --nbufs 32 -f 445600000 -s 1100000 --bw 550e3 -v
Using AD936x FIR interpolator x4
Setting RF bandwidth 550 kHz
Interpolation: ratio 2/1, rolloff 0.350000, 21 coeffs
** IIO: out_voltage_filter_fir_en failed with Unknown error -22

**Comment by unixpunk** [comment]
Have you made sure to stop any other running programs using the radio?  The default is for openwebrx to start at boot.  Set autostart = none or SoapyRemote in config.txt, save and eject.  Then try once more, if you haven't already done this.  Next test would be to see if along with the above, that this works when run from a computer instead of directly on the Pluto.  Let me know how it goes.

**Comment by KR0SIV** [comment]
Thanks, this resolved the issue
